### PR TITLE
Currency Converter

### PR DESCRIPTION
**Pull request by madwork**
This is a proposal to expose a new feature to the API for currency conversion. It used the proposal from #25, which is quite similar to what is done with the google currency tool, but with the time travel feature as a bonus!

As an example, a simple conversion from USD, to EUR:

```
/converter?from=USD&to=EUR&amount=100
```

I'm not sure about the current API response:

```
{ amount: AMOUNT }
```

That could be a bit more exhaustive with the `date`, or the query parameters referenced into the response (maybe into an query object).

If it would be merged into the project, the documentation is still missing, and the errors (and messages) could be better (mainly the one without parameters).

### CODE REVIEW

**Comment by hakanensari** [comment]
Hi @madwork,

My apologies, I overlooked this pull request.

I'm wondering if it would be simpler to expand existing routes by adding an `amount` parameter and aliasing `base` and `symbols` to `from` and `to`, respectively.

``` http
GET /latest?from=USD&to=EUR&amount=100
Host: api.fixer.io
```

The above would then return something like:

``` js
{
  "base": "USD",
  "date": "2016-10-07",
  "rates": {
    "EUR": 89.767
  }
}
```

Alternatively, the response could be tweaked to include the original amount as well. 

What do you think?

**Comment by madwork** [comment]
Hi @hakanensari,

Don't worry, thanks for your feedback.

I don't know, maybe it increases the complexity of `/latest` route a bit too much? We'll need a check on the `amount` parameter presence, it feels not right, what do you think?
If you think that's the better solution, I can have a look to make it work, let me know.

About the JSON result, it's definitely better, I will update it.

**Comment by hakanensari** [comment]
> I don't know, maybe it increases the complexity of `/latest` route a bit too much? 

I've slept on this, and it still feels better to expand the existing route a little further rather than create a new route with duplicate logic. The same way we have a default base, which one can override, we would now also have a default amount.

It's somewhat like how Google's converter works: if you search `JPY in USD`, the amount defaults to 1 while with `10 JPY in USD`, the amount is explicitly set to 10.

**Comment by madwork** [comment]
Ok, interesting, I'll have a look today 👍

**Pull request merged**
