### PR TITLE
add dockerfile and docker-compose.yml

### PR DESCRIPTION
**Pull request by 0x46616c6b**
I want to run fixer-io in our company to prevent a single point of failure, so I create a Dockerfile and a small docker-compose.yml to run it locally. 

What do you think about this approach to run in the Docker Environment? It would be also very nice to extend the readme. It was not so easy - as a non-ruby developer - to start and configure the application.

### CODE REVIEW

**Comment by hakanensari** [comment]
Hi,

This looks good, but I have two questions:
- We probably need to migrate the database and load rates when bootstrapping to have a functional app?

``` sh
rake db:migrate rates:load
```
- How do you handle daily updates when containerising? Fresh install every day or a cron process?

**Comment by 0x46616c6b** [comment]
You can use the image and run the migration against the postgres container. With docker-compose you start the stack with

```
# start fixer and postgres (in foreground)
docker-compose up
# start a container with the command (linked with postgres)
docker-compose run fixer rake db:migrate rates:load
```

**Comment by hakanensari** [comment]
Thanks @0x46616c6b

**Comment by 0x46616c6b** [comment]
@hakanensari can you create a automated build for that on docker? see https://docs.docker.com/docker-hub/github/

**Comment by hakanensari** [comment]
@0x46616c6b, https://hub.docker.com/r/hakanensari/fixer-io/

**Pull request merged**
